image: python:3.9

cache:
  paths:
    - ~/.cache/pip
    - ~/.platformio/.cache

stages:
 - test

before_script:
  - "pip install -U platformio"

job:
  stage: test
  script: "platformio run -e esp32doit-devkit-v1"
  artifacts:
    paths:
      - pio/build/
